spring:
  # Database / JPA
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true

  # GraphQL
  graphql:
    graphiql:
      enabled: true
    schema:
      inspection:
        enabled: true

  docker:
    compose:
      lifecycle-management: 'start_and_stop'